version = 3.11.5
runner.dialect = scala3

maxColumn = 100

align.preset = none
assumeStandardLibraryStripMargin = true

newlines {
  avoidForSimpleOverflow = [tooLong]
}

rewrite {
  rules = [
    AvoidInfix,
    RedundantBraces,
    RedundantParens,
    SortModifiers,
    Imports
  ]
  imports {
    sort = ascii
    groups = [
      ["javax?\\\\..*"],
      ["scala\\\\..*"],
      ["sbt\\\\..*"],
      ["org\\\\..*"],
      ["com\\\\..*"]
    ]
  }
}

trailingCommas = preserve
